### ISSUE TITLE
help

### ISSUE THREAD

**Issue by koecok412** [NotDark/gtcppbot#6]
how to fix automatic dc in 8 minutes?
and add autofarm

**Comment by Gatyu388** [comment]
add ping reply

**Comment by koecok412** [comment]
have discord?

**Comment by koecok412** [comment]
> add ping reply

can i ask at discord?

**Comment by NotDark** [comment]
https://github.com/NotDark/gtcppbot/blob/main/CPPBot/corefunc.h#L507 fixed

**Comment by koecok412** [comment]
how to add auto collect ?
